### ISSUE TITLE
Connect an arbritrary number of devices (local network and beyond)

### ISSUE THREAD

**Issue by jvatic** [jvatic/tauri-bindgen-rs-macros#2]
- [x] Send join request to controller node
- [x] Controller node stores public key & attach status of each agent node in a local DB
- [x] Receive status event(s) from controller node (e.g. accepted, rejected)
- [ ] Agent node stores public key of each controller node it's requested to join & the status of those request(s) in a local DB
- [ ] Controller node provides a UI for managing join/attach requests
- [ ] Agent node provides a UI for managing cluster(s) it's attached to & seeing the status of each attachment
- [ ] Nodes periodically ping each other to see if they're available (perhaps the app isn't running)
