### ISSUE TITLE
Run tasks on nodes in cluster

### ISSUE THREAD

**Issue by jvatic** [jvatic/tauri-bindgen-rs-macros#3]
- [ ] Controller node provides a UI for running a cluster program.
- [ ] Controller node sends `spawn` request(s) to agent node(s) to run a particular wasm binary and provides a SHA2-256 hash along with some other metadata that allows the node to determine if it'll accept or reject the request.
- [ ] Agent accepts or rejects `spawn` requests based on resource quotas (either physical device limitations or those imposed by it's operator).
- [ ] Controller keeps trying to find an agent node to run a `spawn` request when one is rejected, or when a node running a request becomes unresponsive.
- [ ] Agent can fetch & verify the actual wasm binary given it's hash (either from/via the controller node, or from a URL provided in the metadata).
- [ ] Once an agent has accepted a `spawn` request and started running the wasm binary, that program can communicate with it's counterpart on the controller node to exchange data (and vise versa).
- [ ] Agent node caches wasm binaries that have been run recently.
